// 2017-09-06
define([
	'df-lodash', 'jquery', 'ko', 'Df_Phone/lib/js/main'
], function (_, $, ko) {return (
/**
 * 2017-09-06
 * @param {Object} c
 * @param {String[]} c.countries
 * @param {String} c.utils
 */
function(c) {ko.bindingHandlers['df-phone'] = {init: function(e, accessor) {var config = accessor(); var $e = $(e);
	// 2017-09-06 https://github.com/jackocnr/intl-tel-input/blob/v12.0.2/README.md
	$e.intlTelInput(_.extend({
		// 2017-09-06
		// «Whether or not to allow the dropdown.
		// If disabled, there is no dropdown arrow, and the selected flag is not clickable.
		// Also we display the selected flag on the right instead because it is just a marker of state.»
		// Type: boolean. Default: `true`.
		allowDropdown: true
		// 2017-09-06
		// «If there is just a dial code in the input:
		// remove it on blur or submit, and re-add it on focus.
		// This is to prevent just a dial code getting submitted with the form.
		// Requires `nationalMode` to be set to `false`.»
		// Type: boolean. Default: `true`.
		,autoHideDialCode: true
		// 2017-09-06
		// «Set the input's placeholder to an example number for the selected country,
		// and update it if the country changes.
		// You can specify the number type using the `placeholderNumberType` option.
		// By default it is set to "polite",
		// which means it will only set the placeholder if the input doesn't already have one.
		// You can also set it to "aggressive", which will replace any existing placeholder, or "off".
		// Requires the `utilsScript` option.»
		// Type: string. Default: "polite".
		,autoPlaceholder: 'polite'
		// 2017-09-06
		// «Change the placeholder generated by autoPlaceholder. Must return a string.»
		// Type: function. Default: `null`.
		,customPlaceholder: null
		,geoIpLookup: function(callback) {
			$.get('//ipinfo.io', function(){}, 'jsonp').always(function(resp) {
				var countryCode = (resp && resp.country) ? resp.country : '';
				callback(countryCode);
			});
		}
		,initialCountry: 'auto'
		,nationalMode: false
		,onlyCountries: c.countries
		,preferredCountries: []
		,separateDialCode: false
		,utilsScript: c.utils
	}, config.options));
	//$e.blur();
	ko.utils.registerEventHandler(e, 'change', function() {config.storage(this.value);});
	//config.storage('+55 21 3139-8011');
}};});});